CREATE TABLE Multi_Shop (
  Multi_Shop_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Contact_Name VARCHAR(50),
  Location_name VARCHAR(100) NOT NULL,
  Email_Address VARCHAR(100),
  Phone_Number VARCHAR(20),
  Address VARCHAR(150) NOT NULL,
  Business_Hours VARCHAR(150) DEFAULT '09:00 - 18:00',
  Manager_Name VARCHAR(150),
  Number_of_Employees INT DEFAULT 1 CHECK (Number_of_Employees >= 0),
  Additional_Services VARCHAR(255) DEFAULT 'General Repairs'
    CHECK (Additional_Services IN (
      'General Repairs',
      'Bike Wash',
      'Tire Inflation',
      'Chain Lubrication',
      'Accessory Installation',
      'Helmet or Lock Rental',
      'Battery Charging',
      'Bike Storage',
      'Roadside Assistance',
      'Basic Adjustment'
    ))
);

CREATE TABLE Bicycles (
  Bicycle_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Brand VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  Year_Manufacture INT CHECK (Year_Manufacture >= 1970 AND Year_Manufacture <= EXTRACT(YEAR FROM CURRENT_DATE)),
  Type VARCHAR(25) NOT NULL CHECK (Type IN ('Mountain', 'Road', 'Hybrid', 'Electric', 'BMX', 'Other')),
  Color VARCHAR(25),
  Frame_Size VARCHAR(15),
  Maintenance_Status VARCHAR(35) NOT NULL CHECK (Maintenance_Status IN ('Excellent', 'Good', 'Fair', 'Needs Repair')),
  Last_Service_Date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Bicycles_in_Shops (
  DateTime_In DATE NOT NULL,
  DateTime_Out DATE,
  Current_Status VARCHAR(255) NOT NULL CHECK (Current_Status IN ('Available', 'Rented', 'Maintenance')),
  Inventory_Responsible_Person VARCHAR(150),
  Last_Movement_Date DATE DEFAULT CURRENT_DATE,
  Multi_Shop_ID INT NOT NULL,
  Bicycle_ID INT NOT NULL,
  PRIMARY KEY (Multi_Shop_ID, Bicycle_ID),
  FOREIGN KEY (Multi_Shop_ID)
      REFERENCES Multi_Shop(Multi_Shop_ID)
      ON UPDATE CASCADE
      ON DELETE CASCADE,
  FOREIGN KEY (Bicycle_ID)
      REFERENCES Bicycles(Bicycle_ID)
      ON UPDATE CASCADE
      ON DELETE CASCADE,
  CHECK (DateTime_Out IS NULL OR DateTime_Out >= DateTime_In)
);

CREATE TABLE Ref_Payment_Status (
  Payment_Status_Code VARCHAR(5) PRIMARY KEY,
  Payment_Status_Description VARCHAR(50) NOT NULL CHECK (Payment_Status_Description IN ('Pending', 'Paid', 'Overdue', 'Cancelled'))
);

CREATE TABLE Rental_Rates (
  Rental_Rates_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Daily_Rate NUMERIC(10,2) NOT NULL CHECK (Daily_Rate >= 0),
  Hourly_Rate NUMERIC(10,2) NOT NULL CHECK (Hourly_Rate >= 0)
);

CREATE TABLE Renters (
  Renter_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Registration_Date_Time DATE NOT NULL DEFAULT CURRENT_DATE,
  Last_Rental_Date_Time DATE,
  Full_Name VARCHAR(90) NOT NULL,
  Address VARCHAR(250),
  Phone_Number VARCHAR(15) NOT NULL,
  Email_Address VARCHAR(45),
  Date_of_Birth DATE CHECK (Date_of_Birth <= CURRENT_DATE),
  Rental_History INT CHECK (Rental_History >= 0),
  Customer_Rating INT CHECK (Customer_Rating BETWEEN 1 AND 5)
);

CREATE TABLE Ref_Payment_Methods (
  Payment_Methods_Code INT PRIMARY KEY,
  Payment_Method_Description VARCHAR(50) NOT NULL CHECK (Payment_Method_Description IN ('Cash', 'Credit Card', 'Debit Card', 'Mobile Payment'))
);

CREATE TABLE Renters_Payment_Methods (
  Renter_Payment_Method_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Cardholder_Name VARCHAR(150),
  Expiration_Date DATE,
  Issuing_Bank VARCHAR(75),
  Verification_Method VARCHAR(35) DEFAULT 'Manual' CHECK (Verification_Method IN ('Manual', 'PIN', 'Online', 'QR', 'Receipt', 'Biometric')),
  Renter_ID INT NOT NULL,
  Payment_Methods_Code INT NOT NULL,
  FOREIGN KEY (Renter_ID)
      REFERENCES Renters(Renter_ID)
      ON UPDATE CASCADE
      ON DELETE CASCADE,
  FOREIGN KEY (Payment_Methods_Code)
      REFERENCES Ref_Payment_Methods(Payment_Methods_Code)
      ON UPDATE CASCADE
      ON DELETE NO ACTION,
  CHECK (
    (Payment_Methods_Code = 1 AND Cardholder_Name IS NULL) OR
    (Payment_Methods_Code <> 1 AND Cardholder_Name IS NOT NULL)
  ),
  CHECK (Expiration_Date IS NULL OR Expiration_Date >= CURRENT_DATE)
);

CREATE TABLE Rentals (
  Rental_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  All_Day_Rental_YN CHAR(1) NOT NULL CHECK (All_Day_Rental_YN IN ('Y', 'N')),
  Booked_Start_Date_Time DATE NOT NULL,
  Booked_End_Date_Time DATE NOT NULL CHECK (Booked_End_Date_Time >= Booked_Start_Date_Time),
  Actual_Start_Date_Time DATE,
  Actual_End_Date_Time DATE,
  Rental_Payment_Due NUMERIC(10,2) NOT NULL CHECK (Rental_Payment_Due >= 0),
  Rental_Payment_Made NUMERIC(10,2) CHECK (Rental_Payment_Made IS NULL OR Rental_Payment_Made >= 0),
  Employee_in_Charge VARCHAR(255),
  Reservation_Method VARCHAR(255) DEFAULT 'In Person' CHECK (Reservation_Method IN ('In Person', 'Online', 'Phone')),
  Renter_ID INT,
  Bicycle_ID INT,
  Payment_Status_Code VARCHAR(5) NOT NULL,
  Rental_Rates_ID INT NOT NULL,
  Renter_Payment_Method_ID INT,
  FOREIGN KEY (Renter_ID)
      REFERENCES Renters(Renter_ID)
      ON UPDATE CASCADE
      ON DELETE SET NULL,
  FOREIGN KEY (Bicycle_ID)
      REFERENCES Bicycles(Bicycle_ID)
      ON UPDATE CASCADE
      ON DELETE SET NULL,
  FOREIGN KEY (Payment_Status_Code)
      REFERENCES Ref_Payment_Status(Payment_Status_Code)
      ON UPDATE CASCADE
      ON DELETE NO ACTION,
  FOREIGN KEY (Rental_Rates_ID)
      REFERENCES Rental_Rates(Rental_Rates_ID)
      ON UPDATE CASCADE
      ON DELETE NO ACTION,
  FOREIGN KEY (Renter_Payment_Method_ID)
      REFERENCES Renters_Payment_Methods(Renter_Payment_Method_ID)
      ON UPDATE CASCADE
      ON DELETE SET NULL,
  CHECK (Actual_End_Date_Time IS NULL OR Actual_End_Date_Time >= Actual_Start_Date_Time)
);
